### ISSUE TITLE
Question: Possible to configure away parenthsis? 

### ISSUE THREAD

**Issue by hippyau** [Tyill/interpreter#4]
Hi Tyill, 
   I came back to ask a question, and can see you've done a bunch of work since I was last here!

   I wanted to ask about a way to user modify the language, if possible, so simplify to BASICish or perhaps more of a shell thing...

Thanks to your introspection, I can

 ```store(preset(1.2.3));``` for example.

But how to interpret what the user might input like ```store preset 1.2.3```   where it is known:
  ```store``` is a Function, and 
 ```preset``` is a Function, also the argument to ```store```, and 
 ```1.2.3``` is the argument to ```preset```  ... so no (()) required?

**Comment by Tyill** [comment]
Hi.
> I wanted to ask about a way to user modify the language, if possible, so simplify to BASICish or perhaps more of a shell thing...

Quite difficult, because the scripting language is declarative (the user cannot create his own functions arbitrarily, but only call the existing ones) and informal (there are no data types, no structures and arrays as elements of the language).

> But how to interpret what the user might input like store preset 1.2.3 where it is known:

No way, if these are functions, then the parentheses should be. The parentheses define where the arguments end and the next expression begins.
In addition, before parsing the script, all spaces are removed, that is, the parser sees "storepreset1.2.3". And there can be many interpretations.
